version: 2

models:
  - name: int_carrefour_ubications
    description: Intermediate model for processed Carrefour store locations
    columns:
      - name: tipo
        description: Type of store (e.g., Hipermercado, Express)
      - name: direccion
        description: Store address
      - name: localidad
        description: City/locality
      - name: provincia
        description: Province
      - name: hora_apertura
        description: Opening time
      - name: hora_cierre
        description: Closing time
      - name: direccion_con_provincia
        description: Complete address with province and country

  - name: int_vea_sucursales
    description: Intermediate model for processed VEA store locations
    columns:
      - name: sucursal_id
        description: Store ID
        tests:
          - not_null
      - name: nombre_sucursal
        description: Store name
        tests:
          - not_null
      - name: provincia
        description: Province
        tests:
          - not_null
      - name: direccion_principal
        description: Main address extracted from raw data
      - name: direccion_completa
        description: Complete address with province and country
      - name: hora_apertura
        description: Opening time
      - name: hora_cierre
        description: Closing time
      - name: horario_completo
        description: Complete schedule (opening - closing)
      - name: tiene_direccion
        description: Boolean indicator if store has address data
      - name: tiene_horarios
        description: Boolean indicator if store has schedule data
      - name: tiene_telefono
        description: Boolean indicator if store has phone data
      - name: fecha_extraccion_date
        description: Date when data was extracted
